entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"
    http:
      middlewares:
        - "redirect-www@file"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: "web"
    watch: true
  file:
    filename: "/etc/traefik/traefik-dynamic.yml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "tonykabilanokeke@gmail.com"
      storage: "/var/lib/traefik/acme.json"
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: 30
